# Übungsblatt: Pandas Basics 
Ziel: Sie festigen die Grundlagen zu Series, DataFrame, Import/Export, Selektion und Statistik.

Eine gute Übersicht über die Pandas-Funktionen gibt es hier:

- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [Pandas Series](https://pandas.pydata.org/pandas-docs/stable/reference/series.html)
- [Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html)

In den folgenden Aufgaben verwendet ihr einige der meist benutzten Funktionen von Pandas.

## Setup

In [18]:
import pandas as pd

## Aufgabe 1 – Series erstellen (pH-Werte)

Erstellen Sie eine pandas Series mit folgenden pH-Werten:

`7.1, 6.8, 7.4, 7.0, 6.9`

Zusatz: Berechnen Sie den Mittelwert.

In [19]:
ph = pd.Series([7.1, 6.8, 7.4, 7.0, 6.9], name="pH")
ph, ph.mean()

(0    7.1
 1    6.8
 2    7.4
 3    7.0
 4    6.9
 Name: pH, dtype: float64,
 np.float64(7.039999999999999))

## Aufgabe 2 – DataFrame erstellen (Labordaten)

Erstellen Sie einen DataFrame mit folgenden Daten:

| Sample | Temperature_C | OD600 |
|-------|---------------|------|
| A | 30 | 0.45 |
| B | 37 | 0.82 |
| C | 37 | 0.67 |
| D | 30 | 0.50 |

In [20]:
df = pd.DataFrame(
    {
        "Sample": ["A", "B", "C", "D"],
        "Temperature_C": [30, 37, 37, 30],
        "OD600": [0.45, 0.82, 0.67, 0.50],
    }
)
df

  Sample  Temperature_C  OD600
0      A             30   0.45
1      B             37   0.82
2      C             37   0.67
3      D             30   0.50

## Aufgabe 3 – Erste Datenanalyse

Nutzen Sie:
- `.head()`
- `.info()`
- `.describe()`

und beschreiben Sie kurz, welche Informationen jede Methode liefert.

In [21]:
df.head()

  Sample  Temperature_C  OD600
0      A             30   0.45
1      B             37   0.82
2      C             37   0.67
3      D             30   0.50

In [22]:
df.info()  # Datentypen, Non-Null Count, Memory (Überblick über Struktur)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sample         4 non-null      str
 1   Temperature_C  4 non-null      int64
 2   OD600          4 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 228.0 bytes

In [23]:
df.describe()  # Statistische Kennzahlen für numerische Spalten

       Temperature_C     OD600
count       4.000000  4.000000
mean       33.500000  0.610000
std         4.041452  0.168721
min        30.000000  0.450000
25%        30.000000  0.487500
50%        33.500000  0.585000
75%        37.000000  0.707500
max        37.000000  0.820000

## Aufgabe 4 – Spalten auswählen

1) Wählen Sie nur die Spalte `Temperature_C` aus (Series).  
2) Wählen Sie die Spalten `Temperature_C` und `OD600` aus (DataFrame).

In [24]:
temp_series = df["Temperature_C"]
temp_df = df[["Temperature_C", "OD600"]]

temp_series, temp_df

(0    30
 1    37
 2    37
 3    30
 Name: Temperature_C, dtype: int64,
    Temperature_C  OD600
 0             30   0.45
 1             37   0.82
 2             37   0.67
 3             30   0.50)

## Aufgabe 5 – Statistik

Berechnen Sie:
- den Mittelwert der Temperatur
- die Häufigkeit jeder Temperatur (value_counts)
- den Mittelwert von OD600

In [25]:
temp_mean = df["Temperature_C"].mean()
temp_counts = df["Temperature_C"].value_counts()
od_mean = df["OD600"].mean()

temp_mean, temp_counts, od_mean

(np.float64(33.5),
 Temperature_C
 30    2
 37    2
 Name: count, dtype: int64,
 np.float64(0.61))

## Aufgabe 6 – KO Fitness Member einlesen

a. Lesen die Datei `ko_fitness_memberlist_uebung.csv` ein und speicher das Ergebnis in einer Variablen `ko_fitness_memberlist`. 

Wie viele Einträge hat der Dataframe und von welchem Typ sind diese?

- [.info](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)

In [26]:
# Datei einlesen
ko_fitness_memberlist = pd.read_csv(
    "ko_fitness_memberlist_uebung.csv", sep=";", encoding="utf-8"
)
ko_fitness_memberlist.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   member_id   100 non-null    int64
 1   Vorname     100 non-null    str
 2   Name        100 non-null    str
 3   Gewicht     100 non-null    int64
 4   Grösse      100 non-null    float64
 5   Geschlecht  100 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 4.8 KB

b. Gebe die ersten 15 Spalten und die letzten 15 Spalten aus.

- [.head](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html)
- [.tail](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html)

In [27]:
# Ausgabe der letzten 15 Zeilen
ko_fitness_memberlist.tail(15)

    member_id    Vorname      Name  Gewicht  Grösse Geschlecht
85         86     Kathie     Mckie       87    1.73          w
86         87      Elisa   Tassone      103    1.85          w
87         88      Paula    Lovern       60    1.53          w
88         89    Matthew  Odonnell       90    1.68          m
89         90   Nicholas     David       63    1.61          m
90         91      James       Fox      104    1.71          m
91         92    Barbara     Baker       78    1.71          w
92         93     Reggie     Ortiz       75    1.72          m
93         94       Mary    Rivers       99    1.81          w
94         95     Joseph     Mason       62    1.62          m
95         96  Geraldine   Edwards       98    1.54          w
96         97    Charles    Martin       81    1.91          m
97         98       Beth     Rozar       72    1.83          w
98         99    Charles     Owens       98    1.67          m
99        100       Lori   Nichols       81    1.83          w

c. Sie haben eine zusätzliche Liste erhalten mit zusätzlichen Informationen (Geburtsjahr & PLZ) zu den Mitgliedern. Lesen Sie die Datei `ko_fitness_memberlist_additional.csv` ein und ergänzen Sie die Informationen in `ko_fitness_memberlist`. Die Mitglieder sind über die Spalten `member_id` eindeutig identifizierbar.

- [.merge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html)

In [28]:
# Liste mit zusätzlichen Informationen einlesen
ko_fitness_memberlist_additional = pd.read_csv(
    "ko_fitness_memberlist_additional.csv", sep=";", encoding="utf-8"
)
ko_fitness_memberlist_additional

    member_id  Geburtsjahr   PLZ
0           1         1990  8114
1           2         1951  8759
2           3         1967  8250
3           4         1964  8142
4           5         1997  8104
..        ...          ...   ...
95         96         1991  8348
96         97         1957  8300
97         98         1977  8161
98         99         1979  8003
99        100         1996  8896

[100 rows x 3 columns]

In [29]:
# Zusammenführen der beiden DataFrames
ko_fitness_memberlist = pd.merge(
    ko_fitness_memberlist, ko_fitness_memberlist_additional, on="member_id"
)
ko_fitness_memberlist

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ
0,1,Suzanne,Milam,64,1.76,w,1990,8114
1,2,Louis,Finch,99,1.81,m,1951,8759
2,3,Shannon,Francois,101,1.80,w,1967,8250
3,4,Michael,Sinisi,67,1.80,m,1964,8142
4,5,Robert,Mcdonough,90,1.92,m,1997,8104
...,...,...,...,...,...,...,...,...
95,96,Geraldine,Edwards,98,1.54,w,1991,8348
96,97,Charles,Martin,81,1.91,m,1957,8300
97,98,Beth,Rozar,72,1.83,w,1977,8161
98,99,Charles,Owens,98,1.67,m,1979,8003
99,100,Lori,Nichols,81,1.83,w,1996,8896

d. Sie haben zwei neue Listen erhalten. In der einen Liste sind die Mitglieder, die eine Mitgliedschaft gekündigt haben und in der anderen Liste sind die Mitglieder, die eine Mitgliedschaft abgeschlossen haben. Lesen Sie die Dateien `ko_fitness_memberlist_canceled.csv` und `ko_fitness_memberlist_new.csv` ein und ergänzen Sie die Informationen in `ko_fitness_memberlist`. Die Mitglieder sind über die Spalten `member_id` eindeutig identifizierbar.

In [30]:
# Liste mit gekündigten Mitgliedern einlesen
ko_fitness_memberlist_cancelled = pd.read_csv(
    "ko_fitness_memberlist_cancelled.csv", sep=";", encoding="utf-8"
)
ko_fitness_memberlist_cancelled

   member_id
0          5
1         10
2         12
3         48
4         55
5         66
6         68
7         85
8         91

In [31]:
# Mitglieder, die gekündigt haben, aus der Liste entfernen mit for-Schleife
for member_id in ko_fitness_memberlist_cancelled["member_id"]:
    ko_fitness_memberlist = ko_fitness_memberlist[
        ko_fitness_memberlist["member_id"] != member_id
    ]

# Mitglieder, die gekündigt haben, aus der Liste entfernen mit isin()
ko_fitness_memberlist = ko_fitness_memberlist[
    ~ko_fitness_memberlist["member_id"].isin(
        ko_fitness_memberlist_cancelled["member_id"]
    )
]

ko_fitness_memberlist

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ
0,1,Suzanne,Milam,64,1.76,w,1990,8114
1,2,Louis,Finch,99,1.81,m,1951,8759
2,3,Shannon,Francois,101,1.80,w,1967,8250
3,4,Michael,Sinisi,67,1.80,m,1964,8142
5,6,Gerald,Dziuk,80,1.83,m,1993,8758
...,...,...,...,...,...,...,...,...
95,96,Geraldine,Edwards,98,1.54,w,1991,8348
96,97,Charles,Martin,81,1.91,m,1957,8300
97,98,Beth,Rozar,72,1.83,w,1977,8161
98,99,Charles,Owens,98,1.67,m,1979,8003
99,100,Lori,Nichols,81,1.83,w,1996,8896

In [32]:
# neue Mitglieder hinzufügen
ko_fitness_memberlist_new = pd.read_csv(
    "ko_fitness_memberlist_new.csv", sep=";", encoding="utf-8"
)
ko_fitness_memberlist_new.head()

   member_id Vorname       Name  Gewicht  Grösse Geschlecht  Geburtsjahr   PLZ
0        101  Walter    Richter      102    1.92          m         1967  8163
1        102  Walter    Schäfer       63    1.74          m         1980  8227
2        103    Anna      Bauer      108    1.72          w         2000  8892
3        104    Anna  Schneider       53    1.92          m         1975  8336
4        105    Hans      Bauer       58    1.99          w         1972  8656

In [33]:
# Mitgliederliste um neue Mitglieder erweitern
ko_fitness_memberlist = pd.concat(
    [ko_fitness_memberlist, ko_fitness_memberlist_new], ignore_index=True
)
ko_fitness_memberlist

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ
0,1,Suzanne,Milam,64,1.76,w,1990,8114
1,2,Louis,Finch,99,1.81,m,1951,8759
2,3,Shannon,Francois,101,1.80,w,1967,8250
3,4,Michael,Sinisi,67,1.80,m,1964,8142
4,6,Gerald,Dziuk,80,1.83,m,1993,8758
...,...,...,...,...,...,...,...,...
128,138,Ursula,Müller,60,1.91,w,1958,8887
129,139,Renate,Schmidt,56,1.66,w,1970,8216
130,140,Renate,Weber,93,1.98,w,1967,8770
131,141,Hans,Meyer,82,1.55,w,1951,8767
132,142,Karin,Müller,94,1.64,m,1999,8980

e. Und nun berechnen Sie die BMI und BMI-Kategorie für jedes Mitglied und speichern Sie die Ergebnisse in `ko_fitness_memberlist`. Der BMI wird berechnet als Gewicht in Kilogramm geteilt durch das Quadrat der Grösse in Metern. Die BMI-Kategorien sind:

In [34]:
# Funktion bmi_message
def bmi_message(bmi):
    return_val = "Unter 18.5: Untergewicht."
    if bmi > 40:
        return_val = "Über 40: Adipositas Grad III."
    elif bmi >= 35:
        return_val = "35 - 39.9: Adipositas Grad II."
    elif bmi >= 30:
        return_val = "30 - 34.9: Adipositas (Fettleibigkeit) Grad I."
    elif bmi >= 25:
        return_val = "25 - 29.9: Übergewicht/ Präadipositas."
    elif bmi >= 18.5:
        return_val = "18.5 - 24.9: Normalgewicht."
    return return_val


# Funktion bmi_calc
def bmi_calc(weight_in_kg, height_in_m):
    return round(weight_in_kg / height_in_m**2, 2)


# BMI & BMI_Message berechnen mit for-Schleife
bmi_list = []
bmi_message_list = []
for index, row in ko_fitness_memberlist.iterrows():
    bmi = bmi_calc(row["Gewicht"], row["Grösse"])
    bmi_list.append(bmi)
    bmi_message_list.append(bmi_message(bmi))
ko_fitness_memberlist["BMI"] = bmi_list
ko_fitness_memberlist["BMI_Message"] = bmi_message_list

ko_fitness_memberlist

# Das ganze könnte man elegentar gestalten undzwar mit der apply() Methode.
# Dazu werden wir in den nächsten Wochen mehr erfahren

# ko_fitness_memberlist["BMI"] = ko_fitness_memberlist.apply(lambda row: bmi_calc(row["Gewicht"], row["Grösse"]), axis=1)
# ko_fitness_memberlist["BMI_Message"] = ko_fitness_memberlist["BMI"].apply(bmi_message)

# ko_fitness_memberlist

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ,BMI,BMI_Message
0,1,Suzanne,Milam,64,1.76,w,1990,8114,20.66,18.5 - 24.9: Normalgewicht.
1,2,Louis,Finch,99,1.81,m,1951,8759,30.22,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
2,3,Shannon,Francois,101,1.80,w,1967,8250,31.17,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
3,4,Michael,Sinisi,67,1.80,m,1964,8142,20.68,18.5 - 24.9: Normalgewicht.
4,6,Gerald,Dziuk,80,1.83,m,1993,8758,23.89,18.5 - 24.9: Normalgewicht.
...,...,...,...,...,...,...,...,...,...,...
128,138,Ursula,Müller,60,1.91,w,1958,8887,16.45,Unter 18.5: Untergewicht.
129,139,Renate,Schmidt,56,1.66,w,1970,8216,20.32,18.5 - 24.9: Normalgewicht.
130,140,Renate,Weber,93,1.98,w,1967,8770,23.72,18.5 - 24.9: Normalgewicht.
131,141,Hans,Meyer,82,1.55,w,1951,8767,34.13,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
132,142,Karin,Müller,94,1.64,m,1999,8980,34.95,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.

f. Sortien der Mitglieder nach Name und Vorname.
- [.sort_values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html)

In [35]:
# Sortien der Mitglieder nach Name und Vorname.
ko_fitness_memberlist = ko_fitness_memberlist.sort_values(
    by=["Name", "Vorname"], ascending=[True, True]
)
ko_fitness_memberlist

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ,BMI,BMI_Message
82,92,Barbara,Baker,78,1.71,w,1996,8117,26.67,25 - 29.9: Übergewicht/ Präadipositas.
28,32,Mildred,Baker,95,1.70,w,1957,8996,32.87,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
93,103,Anna,Bauer,108,1.72,w,2000,8892,36.51,35 - 39.9: Adipositas Grad II.
95,105,Hans,Bauer,58,1.99,w,1972,8656,14.65,Unter 18.5: Untergewicht.
114,124,Martin,Bauer,65,1.79,m,1979,8683,20.29,18.5 - 24.9: Normalgewicht.
...,...,...,...,...,...,...,...,...,...,...
7,9,William,Waters,94,1.51,m,1952,8030,41.23,Über 40: Adipositas Grad III.
130,140,Renate,Weber,93,1.98,w,1967,8770,23.72,18.5 - 24.9: Normalgewicht.
16,20,Derek,Willett,96,1.59,m,1960,8714,37.97,35 - 39.9: Adipositas Grad II.
40,44,Brandon,Williams,98,1.56,m,1967,8464,40.27,Über 40: Adipositas Grad III.
72,80,William,Zymowski,58,1.61,m,1981,8093,22.38,18.5 - 24.9: Normalgewicht.

g. Speichern Sie die Mitgliederliste in einer neuen Datei `ko_fitness_memberlist_final.xlsx`.
- [.to_excel](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html)

In [36]:
# Speichern Sie die Mitgliederliste in einer neuen Datei `ko_fitness_memberlist_final.xlsx`.
ko_fitness_memberlist.to_excel("ko_fitness_memberlist_final.xlsx", index=False)

h. Lasse dir eine kurze beschreibende Statistik über die Daten ausgeben.

- [.describe](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)

In [37]:
# Lasse dir eine kurze beschreibende Statistik über die Daten ausgeben.
ko_fitness_memberlist.describe(include="all")

,member_id,Vorname,Name,Gewicht,Grösse,Geschlecht,Geburtsjahr,PLZ,BMI,BMI_Message
count,133.000000,133,133,133.000000,133.000000,133,133.000000,133.000000,133.000000,133
unique,NaN,85,100,NaN,NaN,2,NaN,NaN,NaN,6
top,NaN,Hans,Schäfer,NaN,NaN,m,NaN,NaN,NaN,18.5 - 24.9: Normalgewicht.
freq,NaN,8,6,NaN,NaN,73,NaN,NaN,NaN,34
mean,73.030075,NaN,NaN,81.751880,1.735414,NaN,1975.736842,8494.203008,27.725113,NaN
std,41.296221,NaN,NaN,17.420123,0.137331,NaN,14.344197,284.395578,7.558160,NaN
min,1.000000,NaN,NaN,50.000000,1.510000,NaN,1950.000000,8003.000000,12.750000,NaN
25%,37.000000,NaN,NaN,66.000000,1.610000,NaN,1965.000000,8250.000000,22.390000,NaN
50%,74.000000,NaN,NaN,82.000000,1.740000,NaN,1976.000000,8450.000000,27.400000,NaN
75%,109.000000,NaN,NaN,94.000000,1.840000,NaN,1990.000000,8758.000000,32.470000,NaN
max,142.000000,NaN,NaN,118.000000,2.000000,NaN,2000.000000,8996.000000,51.750000,NaN

i. 

Was ist das durschnittliche Gewicht und die kleineste und grösste Körpergrösse?
- [.mean](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)
- [.min](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.min.html)
- [.max](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html)

Wie viele Mitglieder sind männlich und wie viele weiblich? 
- [.value_counts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)

Wie viele einzigartige Nachnamen gibt es? 
- [.nunique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html)

Und was ist der am häufigsten vorkommende Vorname?
- [.value_counts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)
- [.idxmax](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmax.html)

In [38]:
# - durchscnittliches Gewicht: 81.75 kg
mean_weight = ko_fitness_memberlist["Gewicht"].mean()
print(f"Das durchschnittliche Gewicht beträgt: {mean_weight} kg")

# - kleinste Körpergrösse: 1.51 m
min_height = ko_fitness_memberlist["Grösse"].min()
print(f"Die kleinste Körpergrösse beträgt: {min_height} m")

# - grösste Körpergrösse: 2.00 m
max_height = ko_fitness_memberlist["Grösse"].max()
print(f"Die grösste Körpergrösse beträgt: {max_height} m")

# - Anzahl männlich: 73
# - Anzahl weiblich: 60
print(ko_fitness_memberlist["Geschlecht"].value_counts())

# - Anzahl einzigartige Namen: 100
unique_names = ko_fitness_memberlist["Name"].nunique()
print(f"Anzahl einzigartige Namen: {unique_names}")

# - am häufigsten vorkommender Vorname: Hans
most_common_name = ko_fitness_memberlist["Vorname"].value_counts().idxmax()
print(f"am häufigsten vorkommender Vorname: {most_common_name}")

Das durchschnittliche Gewicht beträgt: 81.75187969924812 kg
Die kleinste Körpergrösse beträgt: 1.51 m
Die grösste Körpergrösse beträgt: 2.0 m
Geschlecht
m    73
w    60
Name: count, dtype: int64
Anzahl einzigartige Namen: 100
am häufigsten vorkommender Vorname: Hans

j. Was wiegen alle Mitglieder zusammen?

In [39]:
ko_fitness_memberlist["Gewicht"].sum()

np.int64(10873)